// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHb05QrIJ6D-nj7wbpILDkz29AsCcysis',
    appId: '1:539383804527:web:f48a12754a91f5a87d939a',
    messagingSenderId: '539383804527',
    projectId: 'todolist-6ed62',
    authDomain: 'todolist-6ed62.firebaseapp.com',
    storageBucket: 'todolist-6ed62.appspot.com',
    measurementId: 'G-RR3TTKWGBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdcifTA-gD0CHHPMcayW999_GZV9o3gY',
    appId: '1:539383804527:android:a619ca1275873b3f7d939a',
    messagingSenderId: '539383804527',
    projectId: 'todolist-6ed62',
    storageBucket: 'todolist-6ed62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0gvdUZAUXNeL_N-dNxUI3Z6QaPfX-y0E',
    appId: '1:539383804527:ios:09791f8ce204746a7d939a',
    messagingSenderId: '539383804527',
    projectId: 'todolist-6ed62',
    storageBucket: 'todolist-6ed62.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0gvdUZAUXNeL_N-dNxUI3Z6QaPfX-y0E',
    appId: '1:539383804527:ios:09791f8ce204746a7d939a',
    messagingSenderId: '539383804527',
    projectId: 'todolist-6ed62',
    storageBucket: 'todolist-6ed62.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHb05QrIJ6D-nj7wbpILDkz29AsCcysis',
    appId: '1:539383804527:web:220b250c790420787d939a',
    messagingSenderId: '539383804527',
    projectId: 'todolist-6ed62',
    authDomain: 'todolist-6ed62.firebaseapp.com',
    storageBucket: 'todolist-6ed62.appspot.com',
    measurementId: 'G-2KV21VQM6F',
  );
}
